### ISSUE TITLE
No module named 'custom_components.pik_intercom.const' after update to 0.0.2

### ISSUE THREAD

**Issue by ffrants** [alryaz/hass-pik-intercom#1]
Logger: homeassistant.config_entries
Source: config_entries.py:712 
First occurred: 1:18:48 (1 occurrences) 
Last logged: 1:18:48

Error occurred loading configuration flow for integration pik_intercom: No module named 'custom_components.pik_intercom.const'

Tried to completely reinstall the integration but it didn’t help.

**Comment by alryaz** [comment]
Will rename references, await update to v0.0.3.

**Comment by alryaz** [comment]
Please, try v0.0.3; missing files added

**Comment by ffrants** [comment]
v0.0.3 works like a charm
Thanks!
