### ISSUE TITLE
RTSP поток

### ISSUE THREAD

**Issue by Napalmcold** [alryaz/hass-pik-intercom#12]
Можно ли с камер из этой интеграции получить RTSP поток?
Допустим, чтобы пробросить в Frigate аддон или реализовать возможность записи с камер?

**Comment by dimkawest** [comment]
Тоже интересует этот вопрос! Дайте пожалуйста хотя бы подсказку - как вытащить ртсп поток?

**Comment by alryaz** [comment]
В атрибутах объекта camera он присутствует, гляньте панель разработчика.

**Comment by dimkawest** [comment]
Круто! Спасибо)

**Comment by Napalmcold** [comment]
> В атрибутах объекта camera он присутствует, гляньте панель разработчика.

Так они ведь постоянно меняются. Статичную ссылку возможно сделать?

**Comment by alryaz** [comment]
К сожалению, никак. Примерно так же работает официальное приложение (ссылка действительна не менее 30 минут, но точно не более двух часов).

Компонент использует штатную подсистему `stream` из Home Assistant. Если данная подсистема не предоставляет требуемый функционал, боюсь, решение задачи возможно возложить только на сторонние к компоненту подходы.

Возможно сделать хитрую связку из скриптов, запускающих ffmpeg и переконвертирующих поток, но это уже за гранью данного компонента.

Если Вы пытаетесь завести поток на, например, видеорегистратор, попробуйте периодически обновлять эту ссылку с помощью какой-нибудь команды.
