### ISSUE TITLE
Все Объекты не грузятся на версии 2023.06.1

### ISSUE THREAD

**Issue by ndrewpj** [alryaz/hass-pik-intercom#21]
Внезапно после обновления HA supervised до 2023.06.1 пропали все объекты, камеры и двери.

Ошибка на виджете:
This entity is no longer being provided by the pik_intercom integration. If the entity is no longer in use, delete it in settings.**

**Comment by ndrewpj** [comment]
Вот лог:
File "/config/custom_components/pik_intercom/__init__.py", line 363, in async_setup_entry

**Comment by alryaz** [comment]
Исправлено в v1.1.2
