### ISSUE TITLE
Счетчики воды становятся unavailable

### ISSUE THREAD

**Issue by drakut** [alryaz/hass-pik-intercom#24]
Счетчики после установки компонента показывают значения, но спустя какое-то время становятся unavailable. После перезапуска компонента через Настройки -> Перезапуск снова показывают значения. 
Есть подозрение, что проблема связана с обновлением ссылки сервиса. Видел похожую проблему в другом issue, полагаю тут требуется похожий механизм обновления ссылки, и она не единая для всех устройств после первого запуска.

**Comment by drakut** [comment]
Обратил внимание, в настройках обновления домофона было выставлено 10 минут - через такое же время сенсоры счетчиков становятся unavailable. попробовал увеличить до 24 часов, посмотрим что будет

**Comment by drakut** [comment]
> Обратил внимание, в настройках обновления домофона было выставлено 10 минут - через такое же время сенсоры счетчиков становятся unavailable. попробовал увеличить до 24 часов, посмотрим что будет

Отвалились камеры.. Думаю, обновление ссылки для счетчиков нужно делать отдельно..

**Comment by alryaz** [comment]
Проблема отлажена в версиях v2023.7.3+, но если счётчики продолжают пропадать после перезапуска, без лавинного запроса к серверам ПИК, увы, не обойтись. К сожалению, такое решение предпринимать я не буду.

За время тестирования на 5 учётных записях (v2023.7.4) проблема не выявилась. Если проблема продолжает проявляться, напишите, пожалуйста, в [группу Telegram](https://t.me/alryaz_ha_addons).
