### ISSUE TITLE
Не загружается информация о последнем звонке

### ISSUE THREAD

**Issue by SergCnb** [alryaz/hass-pik-intercom#26]
Все объекты "последнего звонка" в статусе недоступен, в логе наблюдаю следующее:

`Logger: custom_components.pik_intercom.api
Source: custom_components/pik_intercom/api.py:779
Integration: PIK Intercom / ПИК Домофон ([documentation](https://github.com/alryaz/hass-pik-intercom), [issues](https://github.com/alryaz/hass-pik-intercom/issues))
First occurred: 14:03:52 (47 occurrences)
Last logged: 14:07:25

[88] Could not perform current call session, status 404, body: {"error":"Не найдено"}
[89] Could not perform current call session, status 404, body: {"error":"Не найдено"}
[90] Could not perform current call session, status 404, body: {"error":"Не найдено"}
[91] Could not perform current call session, status 404, body: {"error":"Не найдено"}
[92] Could not perform current call session, status 404, body: {"error":"Не найдено"}`

**Comment by SergCnb** [comment]
Вместе с тем в статус недоступен падают и другие объекты last call, в том числе кнопка button.last_call_session_unlocker. Пару версий назад все работало штатно - и грузило инфу о последнем звонке, и открывало дверь этого звонка

**Comment by alryaz** [comment]
@SergCnb протестируйте, пожалуйста, по возможности предрелиз: https://github.com/alryaz/hass-pik-intercom/releases/tag/v2023.7.3

**Comment by SergCnb** [comment]
Поставил
Появился последний звонок со скриншотом в атрибутах, время начала/окончания последнего звонка, информация соответствует действительности

Но вот объект кнопки открытия домофона (последнего звонка) остался в статусе недоступен и кнопку невозможно нажать из интерфейса

Если надо, могу собрать какую-то доп информацию для помощи в поиске проблем. В логах ошибок не пишет сейчас

**Comment by alryaz** [comment]
Объект кнопки будет недоступен, пока не появится незавершённая сессия.

К сожалению, пока что не знаю, как иначе можно отключить кнопку.

**Comment by alryaz** [comment]
Придумал: не буду отключать кнопку, пусть будет открывать последний домофон 👌

**Comment by SergCnb** [comment]
Пару версий назад так и работало )
Кнопка всегда "ссылалась" на "последний домофон"

**Comment by alryaz** [comment]
@SergCnb увы, в связи с тем, что у ПИКа два типа домофонов (абстракции ICM и IoT), кнопку приходится реализовывать сквозь множество этапов. До этого кнопка всегда работала, т.к. работала исключительно схема IoT, для которой открытие было реализовано сразу. Сейчас открытие реализовано для всех четырёх видов сессий: _[(ICM, IoT) * (активная, историческая)]_.

Всё в последней версии. Тут тикет закрываю.
