### ISSUE TITLE
HA 2023.7 не грузится видео с камер

### ISSUE THREAD

**Issue by ndrewpj** [alryaz/hass-pik-intercom#27]
![image](https://github.com/alryaz/hass-pik-intercom/assets/15045174/09aaf1aa-cc4b-4dbb-9828-73d1c3c2d15d)

После обновления и  перезагрузки не грузится видео с камер. До обновления (на v.2023.6.x) работало нормально.

**Comment by ndrewpj** [comment]
пофиксилось апдейтом HA 2027.07.1

**Comment by ndrewpj** [comment]
проблема актуальна на 
HA supervised v 2023.07.1
PIK-intercom v 2023.7.4

**Comment by ndrewpj** [comment]
Апдейт 2023.7.5 исправил проблему.

**Comment by ndrewpj** [comment]
проблема актуальна на
HA supervised v 2023.07.1
PIK-intercom v 2023.7.5

**Comment by alryaz** [comment]
Скиньте, пожалуйста, отладочные логи в телеграм (ссылка на группу в README; можете в ЛС админу группы).

**Comment by ndrewpj** [comment]
скинул несколько недель назад. С последним релизом аддона и HA все так же не работает

**Comment by alryaz** [comment]
@ndrewpj увеличьте частоту (понизьте длительность интервала) обновлений для данных в опциях интеграции. Попробуйте поставить 180 секунд. Минимальное значение – 15 секунд, но я крайне не рекомендую его ставить.

**Comment by ndrewpj** [comment]
> @ndrewpj увеличьте частоту (понизьте длительность интервала) обновлений для данных в опциях интеграции. Попробуйте поставить 180 секунд. Минимальное значение – 15 секунд, но я крайне не рекомендую его ставить.

увеличение времени помогло
