### ISSUE TITLE
не полностью подгружаются объекты

### ISSUE THREAD

**Issue by frenzydrive** [alryaz/hass-pik-intercom#4]
при добавлении учетной записи подгружаются не все объекты недвижимости, привязанные к учетной записи.
У меня два объекта недвижимости, зарегистрированных на учетную запись - подгружается только один, со своими скудами, пробовал настроить как через меню "интеграции", так и через yaml- результат один и тот же, при необходимости готов предоставить дополнительную  информацию

**Comment by frenzydrive** [comment]
у меня два объекта недвижимости зарегистрированных на учетной записи - подгружается только один со своими скудами

**Comment by termit0s** [comment]
похоже такаяже ерунда и у меня.

**Comment by alryaz** [comment]
See #7
