### ISSUE TITLE
не подгружаются camera,switch

### ISSUE THREAD

**Issue by termit0s** [alryaz/hass-pik-intercom#7]
Внезапно пропали камеры.
После удаления и добавления интеграции, камеры и двери не добавляются.
Остался только sensor.last_call_session, но и он не работает.

**Comment by ndrewpj** [comment]
подтверждаю, не работают

**Comment by Shaderz** [comment]
походу чтото поменяли в структуре запросов
у меня тоже не работает

**Comment by ndrewpj** [comment]
автор не откликается на эл. почте

**Comment by evillexus** [comment]
не работает, ни камера, ни свитч

**Comment by alryaz** [comment]
Проблема была связана с неправильным импортом тайпхинта `Hashable` из `collections.*`, что является неверным в Python 3.9+.

**Comment by alryaz** [comment]
Здравствуйте, @termit0s , @Shaderz , @ndrewpj , @evillexus!

Работа над проектом возобновлена. Прошу установить последнюю версию компонента. Она верифицирована относительно приложения ПИК Домофон версии 2021.10.2. Если проблема останется актуальной, прошу написать в Telegram, потребуются учётные данные для сбора информации (или же процесс сбора будет описан).

**Comment by Shaderz** [comment]
Доброго, установил обновление , пока без изменений,  
ни камеры ни управление дверями не доступно. 
удалил и повторно становил интеграцию с настройкой через configuration.yaml, вообще все пропало остался только sensor.last_call_session и тот не доступен

Home Assistant Core  2021.12.9
Supervisor
Версия
supervisor-2021.12.2

в логах пишет без ошибок кроме вот этих подозрительных строчек

2022-01-17 03:11:49 DEBUG (MainThread) [custom_components.pik_intercom.api] [3] Page 1 does not contain data
2022-01-17 03:11:49 DEBUG (MainThread) [custom_components.pik_intercom.api] [4] Page 1 does not contain data

**Comment by alryaz** [comment]
@Shaderz , пожалуйста, напишите в Telegram: [@alryaz](https://t.me/alryaz), нужен дамп ответов.

**Comment by alryaz** [comment]
В ветке `main` имеется первичная поддержка "другого" формата предоставления информации о домофонах (пока что только объекты-открывашки, платформа _switch_).

В теории, предложенное решение должно заработать, однако имеющаяся разница между представимыми структурами данных довольно существенная. Чтобы адаптировать компонент под работу с обоими подходами, потребуется некоторое (неопределённое) время.

**Comment by ndrewpj** [comment]
@alryaz Спасибо за обратную связь. Подтверждаю, после последнего обновления изменений нет, объекты не загружаются.

**Comment by alryaz** [comment]
Проблема идентифицирована: некоторые владения перешли на иной формат публикации объектов, что не поддерживалось версиями <v1.0.0.

v1.0.0 добавляет поддержку сторонних ("новых") объектов домофонов. Если новый релиз не показывает никаких объектов, пожалуйста, создайте новый Issue.
