### ISSUE TITLE
Button instead of switch 

### ISSUE THREAD

**Issue by ffrants** [alryaz/hass-pik-intercom#8]
Относительно недавно, HA выкатил кнопки (https://www.home-assistant.io/integrations/button/). 
Может быть есть смысл переделать switch на button для открытия дверей? Кнопка как-то больше подходит для этого.

**Comment by alryaz** [comment]
Как сильно я за пару месяцев отстал от прогресса...

Спасибо за рекомендацию, ожидайте в v1.1.0.

**Comment by alryaz** [comment]
Поддержка добавлена v1.1.0.

**Comment by alryaz** [comment]
Закрываю Issue (по поводу багов с внедрением, прошу [открыть новый](https://github.com/alryaz/hass-pik-intercom/issues/new/choose); здесь - feature request).
