### ISSUE TITLE
Last call session

### ISSUE THREAD

**Issue by dimkawest** [alryaz/hass-pik-intercom#9]
Привет! Спасибо за обновление! Заработало видео, кнопки открытия (раньше ничего не работало).
Но до сих пор у меня не работает сенсор последнего звонка.

**Comment by alryaz** [comment]
Здравствуйте! Исправлю в грядущем обновлении.

**Comment by Napalmcold** [comment]
Добрый день! Есть новости по сенсору?

**Comment by alryaz** [comment]
Пропала возможность тестировать компонент (нет учётной записи, сам не ПИКовец), поэтому пока что новостей нет. (Недавно один пользователь отозвался, однако пока что не было времени поработать над компонентом).

По поводу обновления по факту звонка и событий: на данном этапе пока что только выявил, что можно работать через ловлю пуш-уведомлений, но какого-то штатного решения для этого нет. Опять же, упомянутый пользователь заслал мне документацию API, которое, вероятно, описывает данный вариант использования; изучать буду на следующей неделе.

**Comment by exstrim401** [comment]
Можете проверить, работает ли сенсор у вас в новой версии?

**Comment by dimkawest** [comment]
> Можете проверить, работает ли сенсор у вас в новой версии?

Не работает:
-после обновления не заработал (недоступен);
- дальше я удалил интеграцию и настроил заново - сенсор вообще не появляется. 
-после настроек звонил в домофон.

**Comment by exstrim401** [comment]
> > Можете проверить, работает ли сенсор у вас в новой версии?
> 
> Не работает: -после обновления не заработал (недоступен);
> 
>     * дальше я удалил интеграцию и настроил заново - сенсор вообще не появляется.
>       -после настроек звонил в домофон.

Можете тогда добавить в конфиг:
```
logger:
  default: warning
  logs:
    custom_components.pik_intercom: debug
```
затем залить лог на https://pastebin.com/ и отправить?
удалите только из лога ваш адрес для анонимности

**Comment by dimkawest** [comment]
> logger

https://pastebin.com/20fsHzNw

если нужно еще что-то - пиши

**Comment by dimkawest** [comment]
> > > Можете проверить, работает ли сенсор у вас в новой версии?
> > 
> > 
> > Не работает: -после обновления не заработал (недоступен);
> > ```
> > * дальше я удалил интеграцию и настроил заново - сенсор вообще не появляется.
> >   -после настроек звонил в домофон.
> > ```
> 
> Можете тогда добавить в конфиг:
> 
> ```
> logger:
>   default: warning
>   logs:
>     custom_components.pik_intercom: debug
> ```
> 
> затем залить лог на https://pastebin.com/ и отправить? удалите только из лога ваш адрес/логин/пароль


https://pastebin.com/20fsHzNw


если нужно еще что-то - пиши

**Comment by dimkawest** [comment]
> > > Можете проверить, работает ли сенсор у вас в новой версии?
> > 
> > 
> > Не работает: -после обновления не заработал (недоступен);
> > ```
> > * дальше я удалил интеграцию и настроил заново - сенсор вообще не появляется.
> >   -после настроек звонил в домофон.
> > ```
> 
> Можете тогда добавить в конфиг:
> 
> ```
> logger:
>   default: warning
>   logs:
>     custom_components.pik_intercom: debug
> ```
> 
> затем залить лог на https://pastebin.com/ и отправить? удалите только из лога ваш адрес/логин/пароль

Привет! Получилось что-нибудь сделать с сенсором последних звонков? 
1. я нашел историю звонков в ЛК на сайте https://iot.rubetek.com/geo_units/******
2. и еще в инструкции от домофона есть такая инфа https://rubetek.com/upload/iblock/851/851d1865c42cf3937b1e70f44e6e4386.pdf : 
_"Уведомление о вызове: Эта функция позволяет отправлять
уведомление. Когда пользователь
совершает звонок, система выполнит захват
изображения и его отправку.
Поддерживается три типа: FTP, Email,
HTTP. Для установки FTP и Email в
интерфейсе Домофон.Уведомления.
произведите необходимые настройки. При
выборе режима HTTP, введите URL в
формате: http://адрес IP сервера (пример:
23
http://192.168.35.48/) "_

**Comment by exstrim401** [comment]
@dimkawest привет! к сожалению, я переехал и теперь нет доступа к домофону ПИК(

**Comment by alryaz** [comment]
Товарищи, `last_call_session` заменён на новый сенсор, который быстрее срабатывает в бета-версии.

Для получения статуса звонка потребуется, видимо, либо пользоваться SIP-ом, либо ~~отлавливать пуши~~ (не сработало).

Описанный в PDF, предоставленном @dimkawest , метод работает только при наличии прямого доступа к домофону. К сожалению, это вряд ли возможно.

Прошу всех протестировать 2023.6.*; данный тикет я вынужден закрыть вследствие утери актуальности. Информация будет в дальнейшем использована (отдельное спасибо @exstrim401 за PR!).
